version: '3.8'

services:
  # 1. PostgreSQL (Banco Relacional)
  postgres:
    image: postgis/postgis:15-3.3 # Imagem oficial com suporte espacial
    container_name: portfolio-postgres
    ports:
      - "5433:5432" # Mapeando 5433 (seu pc) para 5432 (container)
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: paulo
      POSTGRES_PASSWORD: tresdois
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis (Cache)
  redis:
    image: redis:alpine
    container_name: portfolio-redis
    ports:
      - "6379:6379"

  # 3. MongoDB (Logs)
  mongo:
    image: mongo:latest
    container_name: portfolio-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 4. MinIO (Arquivos/S3)
  minio:
    image: quay.io/minio/minio
    container_name: portfolio-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console Visual
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  mongo_data:
  minio_data: